### ISSUE TITLE
Documentation on how to add data for other geographies 

### ISSUE THREAD

**Issue by esirK** [OpenUpSA/wazimap-ng#107]
Firstly thank you for an amazing product. 
I have been able to set up the wazimap-ng project and populate the database using the provided database dump. However, I would like to add data for other countries other than **South Africa**. From the code, I have seen a management command that allows me to load geographies and I have also been able to use the admin dashboard to add some datasets. Despite this, I would like to know if you have a documentation on how to add data for another country or if it's possible to give me directions on how to do this. Thank you.

**Comment by esirK** [comment]
@adieyal apologies for tagging you but I've seen you're a long time contributor so I decided to ask if you might have any pointers on the above.

**Comment by adieyal** [comment]
Hi esirK

Thanks for the email and apologies for not seeing your earlier message. I'll write up some documentation and link you to it. The tool is under active development so expect frequent changes. We are also improving the bootstraping process to make it easier for new developers to get started.

**Comment by adieyal** [comment]
I've created a tutorial based on something I wrote previously. It might be a little verbose as it goes through the process of creating the shapefiles but hopefully it provides enough information to get you started. Let me know if you have any questions or whether you think additional explanations would be useful: 

[https://app.gitbook.com/@openup/s/wazi-ng-technical/tutorials/loading-new-geographies](https://app.gitbook.com/@openup/s/wazi-ng-technical/tutorials/loading-new-geographies)

**Comment by esirK** [comment]
Thank you very much for this @adieyal  I will go through it today and in case I have questions I'll reach out.

**Comment by adieyal** [comment]
@esirK Can I close this issue?

**Comment by esirK** [comment]
@adieyal  sure I was able to do the setup using the docs provide. Forgot to close the issue.

**Comment by adieyal** [comment]
👍
