### ISSUE TITLE
Cache invalidation changes

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng#139]
related to #124
and PR: #132 

## Group
Get the dataset for a group.
Find each profile for that dataset
Invalidate profile cache for each profile

## Geography
Get the Hierarchy
Every profile that uses that hierarchy should be invalidated

**Comment by goyal1092** [comment]
PR: https://github.com/OpenUpSA/wazimap-ng/pull/144

https://github.com/OpenUpSA/wazimap-ng/blob/staging/wazimap_ng/cache.py#L123
We already have cache update signal for Group and one group will only be linked to one dataset and one profile.

**Comment by milafrerichs** [comment]
> We already have cache update signal for Group and one group will only be linked to one dataset and one profile.
@goyal1092 
As far as I understood it: 
a group belongs to a dataset. and a dataset has an "owner" profile. 
but if it's made public the dataset can be used by different profiles that's why we need to find the profiles that uses that dataset and invalidate those.

**Comment by goyal1092** [comment]
Got your point @milafrerichs 
Fixing right now

**Comment by goyal1092** [comment]
@milafrerichs I have updated PR for group cache update and test accordingly.
