### ISSUE TITLE
Profile Indicators from one profile displaying on another profile if they are derived from the same variable.

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng#176]
I'm not 100% that this is the case but here is the process

1. Navigate to http://beta.youthexplorer.org.za/
2. Open rich data view
3. Scroll to Language most spoken at home
4. Notice that the x-axis ends at 100%
5. Open the admin suite to this profile indicator: https://production.wazimap-ng.openup.org.za/admin/profile/profileindicator/175/change/ - note that th profil is BPS not youth explorer
6. Change the maxX to 0.5 and save it
7. Refresh the rich data view, notice the change in the x axis.

This should not happen. The indicator that should be affect the output is this one: https://production.wazimap-ng.openup.org.za/admin/profile/profileindicator/85/change/

0.12

https://trello.com/c/1HlvZUt5/603-profile-indicators-from-one-profile-displaying-on-another-profile-if-they-are-derived-from-the-same-variable

**Comment by goyal1092** [comment]
@milafrerichs This issue will be fixed when : https://github.com/OpenUpSA/wazimap-ng/pull/215/files is merged.
