### ISSUE TITLE
Adding a new profile indicator does not invalidate the cache

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng#197]
V 1.0

https://trello.com/c/w1pSl099/627-adding-a-new-profile-indicator-does-not-invalidate-the-cache

**Comment by goyal1092** [comment]
@milafrerichs Adding a new profile indicator is invalidating cache for me in all_details view
Is there any other view i should check ?

**Comment by milafrerichs** [comment]
great. thanks for checking. 

but deleting an indicator does not invalidate it. can you add that? @goyal1092

**Comment by goyal1092** [comment]
Hello @milafrerichs 
I have updated PR: https://github.com/OpenUpSA/wazimap-ng/pull/240
to run cache refresh if data is deleted (for Profile indicator and other models too)
Please review now
