### ISSUE TITLE
Create dataset upload API endpoints

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng#238]
Staging area

https://trello.com/c/nTNIyOQZ/700-create-dataset-upload-api-endpoints

**Comment by milafrerichs** [comment]
The following things are needed after the data upload completed:

* update all indicators that uses this specific dataset (probably by adding a param to the request, like `update=True` )
* ability to create a token from the admin interface
Some kind of notification. either
* create a pullable status endpoint for each uploaded dataset (is it complete, did it fail)
* send email notification to user who uploaded the data
