### ISSUE TITLE
staging backend crashes when requesting WORLD geography on profile 16 (ccij-water)

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng#291]
Staging area (0.13 cont)

https://trello.com/c/xqiF45ku/773-staging-backend-crashes-when-requesting-world-geography-on-profile-16-ccij-water

**Comment by milafrerichs** [comment]
@michaelglenister1 
https://github.com/OpenUpSA/wazimap-ng/blob/staging/wazimap_ng/profile/serializers/metrics_serializer.py#L15
